### ISSUE TITLE
Other versions of dump

### ISSUE THREAD

**Issue by GittiHab** [fabiomercorio/GraphDBLP#1]
Hello,
we would like to use your graph version of DBLP for relationship prediction over time. Therefore we would need other versions of the graph. Do you have such or do you have a script that could generate new dumps?

Thank you!

**Comment by fabiomercorio** [comment]
Hi, sorry for the late reply. You can download DBLP datasets from http://dblp.uni-trier.de or (better) you might plan to use the aminer citation network (http://aminer.org/citation) that also includes abstracts and citations. Then, the dump has to be loaded into Neo4j as you prefer (XML reader through Python is preferable).
Hope this helps
